### ISSUE TITLE
Using VavrModule causes bad type serialization when serializing Option.

### ISSUE THREAD

**Issue by RNowak4** [vavr-io/vavr-jackson#114]
When Option object includes an object extending abstract class or implementing an interface, then VavrModule serializes only getters or fields from abstract class.

For example
`abstract  class A {
public int i;
}`

`class B extends A {
public double d;
}`

Result of serialization `Option<A> o = Option.of(new B())` will result in serialization of only field `i` without field `d`.

**Comment by RNowak4** [comment]
Fix in: https://github.com/vavr-io/vavr-jackson/pull/115

**Comment by ruslansennov** [comment]
Hi @RNowak4 
Could you provide your reproducer as a test?

**Comment by RNowak4** [comment]
Done :)
