### ISSUE TITLE
Support deserializeNullAsEmptyCollection for Maps

### ISSUE THREAD

**Issue by sLite** [vavr-io/vavr-jackson#131]
Is there a reasoning or technical reason behind the fact that the MapLikeDeserializers doesn't honor `deserializeNullAsEmptyCollection` setting like the CollectionLikeDeserializers do?

Would you accept a PR for this, and if yes, would you prefer a new Setting `deserializeNullAsEmptyMap` or extend the scope of the existing one?

**Comment by ruslansennov** [comment]
Hi @sLite 
No, there is no reasoning, PR are welcome, thanks.
I believe `deserializeNullAsEmptyCollection` is enough and we don't need a new setting flag.

**Comment by sLite** [comment]
Ok, thanks, i will give it a try this weekend :)

**Comment by mincong-h** [comment]
Hi @sLite , I implemented this feature since I saw that the issue was not active since one year. Hope you don't mind.
