### ISSUE TITLE
Cannot deserialize/serialize YearMonth / LocalDateTime with specific JsonFormat

### ISSUE THREAD

**Issue by lukaszs7** [vavr-io/vavr-jackson#141]
For POJO with @JsonCreator I cannot set @JsonFormat if certain property has Option type. e.g.:

- `@JsonProperty(value = "operatingMonth") @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = IHubConstants.YEAR_MONTH_FORMAT) Option<YearMonth> operatingMonth`
I've got:

`Cannot deserialize value of type `java.time.YearMonth` from String "05-2019"`

For LocalDateTime and other java.time classes same problem occurred. Do you have some workaround for time being, other than custom Serializer/Deserializer?

**Comment by mincong-h** [comment]
Hi @lukaszs7 , I spent some time to investigate your issue and here what I found.

> For LocalDateTime and other java.time classes same problem occurred. Do you have some workaround for time being, other than custom Serializer/Deserializer?

Serializing and deserializing Java Time classes are not supported by default by Object Mapper. You need to declare additional dependency on [Jackson Java 8 Date/Time](https://github.com/FasterXML/jackson-modules-java8/tree/master/datetime) and register module `JavaTimeModule`. Once you registered that module, Jackson know how to serialize and deserialize your `java.time` classes. In you case, you use `java.time.YearMonth`, `JavaTimeModule` will use [`YearMonthSerializer`](https://fasterxml.github.io/jackson-datatype-jsr310/javadoc/2.7/com/fasterxml/jackson/datatype/jsr310/ser/YearMonthSerializer.html) and [`YearMonthDeserializer`](https://fasterxml.github.io/jackson-datatype-jsr310/javadoc/2.7/com/fasterxml/jackson/datatype/jsr310/deser/YearMonthDeserializer.html). Here is how you can declare dependency in Maven and register the module in Java.

```xml
<!-- Declare dependency on Jackson Java 8 Date/Time --> 
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
    <version>${jackson.version}</version>
</dependency>
```

```java
ObjectMapper mapper = new ObjectMapper()
   .registerModule(new JavaTimeModule()); // new module, NOT JSR310Module
```

You can see more help in the "Usage" section of https://github.com/FasterXML/jackson-modules-java8

In your case, there is some particularity. You use custom JSON format via `@JsonFormat`. This is completely fine, but I have proof that VAVR module does not support it. The JSON format pattern "MM-yyyy" is not passed correctly from OptionSerializer to YearMonthSerializer. After comparing VAVR's `OptionSerializer` and Jackson JDK 8's `OptionalSerializer`, I believe the difference is that VAVR's `OptionSerializer` does not implement interface [ContextualSerializer](https://github.com/FasterXML/jackson-databind/blob/2.11/src/main/java/com/fasterxml/jackson/databind/ser/ContextualSerializer.java), so the context is lost. So I think this is a bug, @ruslansennov . The complete reproduction steps are available in my folk, see commit https://github.com/mincong-h/vavr-jackson/commit/bb7929692999572e2ab1db9c256d9efa39cd3f66 Unfortunately, I don't have enough time to work on it this week...

Here is a workaround I propose: serialize and deserialize without option for `YearMonth` attribtues and create option in the getter method:

```java
class MyVavrOptionalWorkaround {
    @JsonProperty("operatingMonth")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "MM-yyyy")
    YearMonth operatingMonth;

    Option<YearMonth> getOperatingMonth() {
        return Option.of(operatingMonth);
    }
}
```

**Comment by lukaszs7** [comment]
I've already added Jackson JavaTimeModule. But as you wrote, my problem only exists if you want to pass jsonformat. I've already fixed my issue with custom option Java time serializer. But for sure it's VAVR bug so it will be nice to use your fix in next VAVR releases :) thanks

**Comment by ruslansennov** [comment]
@lukaszs7 @mincong-h thank you guys. I am afraid that the same problems may appear in another deserializer (for example, in a `LazyDeserializer`), but this should be checked in another issue

**Comment by mincong-h** [comment]
@ruslansennov thanks, I created a new issue for that. I will check it and other serializer / deserializers in the coming days.
