### ISSUE TITLE
MaplikeDeserializer will always use a keyComparator based on String::compareTo. 

### ISSUE THREAD

**Issue by drewctaylor** [vavr-io/vavr-jackson#142]
I'm using vavr-jackson as a model for a serialization module I'm writing, and I discovered that this conditional:

https://github.com/vavr-io/vavr-jackson/blob/0965498ba5f6825f8a1202c013bbcfa3e6a0fba4/src/main/java/io/vavr/jackson/datatype/deserialize/MaplikeDeserializer.java#L49-L55

Will always evaluate to false (`isAssignableFrom` returns true only if the raw class is a supertype of Comparable, which it cannot be).

You probably want the reverse:

```java 
if (Comparable.class.isAssignableFrom(keyType.getRawClass())) {
    keyComparator = (Comparator<Object> & Serializable) (o1, o2) -> ((Comparable) o1).compareTo(o2);
} else {
    keyComparator = (Comparator<Object> & Serializable) (o1, o2) -> o1.toString().compareTo(o2.toString());
}
```

This might be most noticeable for ordered, map-like objects whose keys are the values of an enum; the default ordering for the values of the enum is the order they are defined (which may not be alphabetical).

**Comment by ruslansennov** [comment]
@drewctaylor thanks for the report
