### ISSUE TITLE
Better support raw type reference in VAVR

### ISSUE THREAD

**Issue by miguelaferreira** [vavr-io/vavr-jackson#150]
Thanks for the great library. It's really nice to be using vavr collections "all-the-way". 
I was experimenting with this module in a few of my projects and I noticed that on Java 11 and above I always get the same exception running the example on the README

Example
```java
String json = mapper.writer().writeValueAsString(List.of(List.of(1)));
// = [[1]]
Object restored1 = mapper.readValue(json, List.class);
// = List(java.util.ArrayList(1))
Object restored2 = mapper.readValue(json, new TypeReference<List<List<?>>>() {});
// = List(List(1))
```

This is the output
```
json = [[1]]

java.lang.IncompatibleClassChangeError
	at io.vavr.jackson.datatype.deserialize.SeqDeserializer.create(SeqDeserializer.java:63)
	at io.vavr.jackson.datatype.deserialize.SeqDeserializer.create(SeqDeserializer.java:34)
	at io.vavr.jackson.datatype.deserialize.ArrayDeserializer.deserialize(ArrayDeserializer.java:63)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
	at Test.name(Test.java:19)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

My question is: Does the module support java versions above 8? Or is this error expected?

**Comment by mincong-h** [comment]
Hi @miguelaferreira , I just checked the support for JDK 11 and JDK 14 (https://github.com/vavr-io/vavr-jackson/pull/151), everything is working as expected. About the type reference problem, I don't know much about the internal implementation. Need help from other contributors.

**Comment by miguelaferreira** [comment]
Thanks for getting back to me @mincong-h. I will re-do my testing, maybe something got messed up. I'll post here my findings.

**Comment by mincong-h** [comment]
Your example was good, @miguelaferreira . I wrote a test yesterday and I can confirm your issue (see "FIXME"):

```java
public class Issue150Test extends BaseTest {

    @Test
    void itShouldDeserializeListList() throws IOException {
        String json = mapper().writeValueAsString(List.of(List.of(1)));
        assertEquals("[[1]]", json);

        // FIXME
//      List<List<Integer>> list = mapper().readValue(json, List.class);
//      assertEquals(List.of(1), list.get(0));

        List<List<Integer>> listFromRef = mapper().readValue(json, new TypeReference<List<List<Integer>>>() {
        });
        assertEquals(List.of(1), listFromRef.get(0));
    }

    @Test
    void itShouldDeserializeListListFromClass() throws Exception {
        MyClass obj = new MyClass(List.of(List.of(1)));
        String json = mapper().writeValueAsString(obj);
        assertEquals("{\"t\":[[1]]}", json);

        MyClass deserialized = mapper().readValue(json, MyClass.class);
        assertEquals(List.of(List.of(1)), deserialized.table);
    }

    static class MyClass {
        @JsonProperty("t")
        List<List<Integer>> table;

        @JsonCreator
        MyClass(@JsonProperty("t") List<List<Integer>> table) {
            this.table = table;
        }
    }

}
```

But I didn't have time to investigate how it works internally...

**Comment by miguelaferreira** [comment]
Thanks again for the investigation @mincong-h. In order to use vavr collections in my model and still have it serialise/deserialise the broken case (the one you marked with `//FIXME`) is what I need. I will look into it and see if I can debug it.

**Comment by ruslansennov** [comment]
Hi guys. It seems we should fix README.md

**Comment by miguelaferreira** [comment]
I'm not sure what you mean exactly @ruslansennov. I trying to debug this issue I've cloned the project and added a test like the one from @mincong-h. Turns out that there it works.

Here's the test
```java
    @org.junit.jupiter.api.Test
    void issue150Test() throws Exception {
        System.out.println(System.getProperty("java.version"));

        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new VavrModule());

        String json = mapper.writer().writeValueAsString(List.of(List.of(1)));
        // = [[1]]
        System.out.println("json = " + json);

        Object restored1 = mapper.readValue(json, List.class);
        // = List(java.util.ArrayList(1))
        System.out.println("restored1 = " + restored1);

        Object restored2 = mapper.readValue(json, new TypeReference<List<List<?>>>() {
        });
        // = List(List(1))
        System.out.println("restored2 = " + restored2);
    }
```

And the output 
```
Test > issue150Test() STANDARD_OUT
    14
    json = [[1]]
    restored1 = List([1])
    restored2 = List(List(1))
```

I will try to create a jar myself with the same java version I'm using in my project and see if that will work.

**Comment by miguelaferreira** [comment]
I've compiled the jar using Java 14 JDK and then I pulled in the local jar into my project and that fixed the error.

**Comment by mincong-h** [comment]
> And the output
> 
> ```
> Test > issue150Test() STANDARD_OUT
>     14
>     json = [[1]]
>     restored1 = List([1])
>     restored2 = List(List(1))
> ```

This is not really working. `[1]` is the string representation of Java list while `List(1)` is the representation of VAVR list. They look quite similar. Here is the pseudo code for type representation:

- `List([1])`: `io.vavr.collection.List(java.util.ArrayList(1))`
- `List(List(1))`: `io.vavr.collection.List(io.vavr.collection.List(1))`

JUnit didn't complain because you removed the assertions from my example.

**Comment by miguelaferreira** [comment]
Fair enough @mincong-h. What I meant to say is that I can now run through the example in the README.md and not get an exception.

**Comment by pivovarit** [comment]
If I understand correctly, the core issue was some mixup with jar files compiled using various JDK versions, right? If not, feel free to reopen :)
