### ISSUE TITLE
compile and release against 1.0.0-alpha-3

### ISSUE THREAD

**Issue by domdorn** [vavr-io/vavr-jackson#153]
The sourcecode of this module is source-compatible to vavr-1.0.0-alpha-3 but not binary compatible. 
because of this, using the module together with `'io.vavr', name: 'vavr', version: '1.0.0-alpha-3'` results in `java.lang.IncompatibleClassChangeError`s

please release a new version which is simply compiled against 1.0.0-alpha-3

**Comment by ruslansennov** [comment]
done
https://repo1.maven.org/maven2/io/vavr/vavr-jackson/1.0.0-alpha-3/

**Comment by domdorn** [comment]
Thanks a lot, works like a charm!
