### ISSUE TITLE
Update Dependencies: Transitive vulnerable dependency jackson-databind

### ISSUE THREAD

**Issue by superduper** [vavr-io/vavr-jackson#192]
Hi! 

I've noticed quite a long list of CVEs associated with one of dependencies that `0.10.3` relies on. Do you think it's safe to simply bump version to a non-vulnerable one?

![image](https://user-images.githubusercontent.com/902950/194292486-b0b7fba1-f23e-49a4-889f-2a22846978ac.png)

**Comment by pivovarit** [comment]
The library compiles against a historical version for backward compatibility reason - it's perfectly normal and expected to bump Jackson to newer versions
