### ISSUE TITLE
vavr-jackson-0.10.4 missing

### ISSUE THREAD

**Issue by moledzki** [vavr-io/vavr-jackson#193]
Hi,

Latest vavr-jackson package available in maven repository is 0.10.3, version 0.10.4 is missing. Is it intentional or a bug?

**Comment by fritteli** [comment]
I'd also like to know that.
Also, is there a problem using vavr-jackson-0.10.3 together with vavr-0.10.4?

**Comment by pivovarit** [comment]
I believe it was intentional because there were no changes ready to be published alongside vavr `0.10.4`. Anyway, `0.10.5` is coming and will address most of the issues and provide compatibility with latest Jackson versions
