### ISSUE TITLE
gradle-nexus-plugin is not compatible with Gradle 7

### ISSUE THREAD

**Issue by mincong-h** [vavr-io/vavr-jackson#196]
https://github.com/bmuschko/gradle-nexus-plugin is archived and it's not compatible with Gradle 7. It means that:

* Upgrading to Gradle 7 is blocked until we find a replacement of the cradle-nexus-plugin
* We cannot test JDK 17 because the Java version is not recognized by Gradle 6 ...

**Comment by bmscomp** [comment]
I make a pull request that tries to find a replacement for plugin and upgraded to Gradle 7.6 and now we can test on jdk 17 and also jdk 19

**Comment by mincong-h** [comment]
Fixed by https://github.com/vavr-io/vavr-jackson/pull/198, thank you @bmscomp
