### ISSUE TITLE
Check `deserialize(serialize(o)) equals o` for all

### ISSUE THREAD

**Issue by ruslansennov** [vavr-io/vavr-jackson#75]
See [this](https://github.com/javaslang/javaslang-jackson/issues/73#issuecomment-246592921) comment

**Comment by jezovuk** [comment]
There is a problem with SortedMap, similar to the one with SortedSet (which was fixed in #73).

**Comment by ruslansennov** [comment]
@jezovuk thank you, fixed

**Comment by jezovuk** [comment]
Thanks!
